### ISSUE TITLE
有没有考虑过富文本点击问题

### ISSUE THREAD

**Issue by zhouzhuo810** [aishang5wpj/RichEditTextPro#3]
貌似部分手机editText.setMovementMethod(LinkMovementMethod.getInstance());
会导致点击输入框的时候光标回到原点再回来，很奇葩。
目前也没找到解决方案，有机会可以一起探讨一下。

**Comment by aishang5wpj** [comment]
最近比较忙已经很久没看这个项目了

**Comment by zhouzhuo810** [comment]
好吧
