### ISSUE TITLE
请问如何添加附加信息

### ISSUE THREAD

**Issue by HeYongRui** [aishang5wpj/RichEditTextPro#5]
请问如何将附加信息添加到ImageSpan中，高亮的clickSpan的内容中是否可以直接解析附加信息(例如id等)，是否也需要将附加信息上传到后台

**Comment by aishang5wpj** [comment]
你可以继承一个ImageSpan，暂时叫ImageSpanPro吧，你设置Image的时候就用ImageSpanPro去设置，解析的时候用ImageSpanPro去解析，然后ImageSpanPro对象里有哪些属性你自己决定就行了，比如id等，要不要传到后台看你们业务的逻辑了

**Comment by HeYongRui** [comment]
@aishang5wpj thx~
